### ISSUE TITLE
Error with the latest vscube (test version)

### ISSUE THREAD

**Issue by Asd-g** [FranceBB/LinearTransformation#2]
Error with the latest vscube (test version):

![00002-073000000](https://github.com/FranceBB/LinearTransformation/assets/65298684/48858027-a663-40c3-8f0c-7eccc3f0aff6)

**Comment by FranceBB** [comment]
Fixed.
Line 155 had to be changed from fullrange=true to fullrange=1 as it's now an integer and no longer a boolean.
I changed it.
Since I was there, I also specified interp=1 to make it use tetrahedral interpolation instead of trilinear.
Ironically I was the one who updated the Wiki but forgot to update my own function xD

**Comment by FranceBB** [comment]
https://github.com/FranceBB/LinearTransformation/releases/tag/2.4

**Comment by Asd-g** [comment]
Thanks.
