### ISSUE TITLE
It seems that MaskSubMod() does not support VSFilterMod?

### ISSUE THREAD

**Issue by mojie126** [FranceBB/LinearTransformation#3]
It seems that MaskSubMod() does not support VSFilterMod
`
LoadPlugin("D:/afd/DGCube.dll")
LoadPlugin("D:/afd/VSFilterMod.dll")
MaskSubMod("D:/afd/a-mmrq14.ass", 1920, 1080, 23.97599983215332, 51424)
ConvertBits(16)
ConvertToPlanarRGBA()
DGCube("D:/afd/BT709_to_PQ.cube")
`

**Comment by FranceBB** [comment]
The issue here is that Cube() along with DGCube() only accept RGB planar 16bit, without the alpha channel.
Luckily there's a "trick" or rather a "workaround" shall I say.
Essentially the alpha channel is literally just one additional channel on top of the normal RGB, which means that it can absolutely be treated separately as if it was just a normal, fake, RGB, and then added back.
I actually had to do something similar when I had to convert the logos coming from the graphics department from BT709 SDR to BT2020 HLG (you're going to PQ but it's the same thing for all intents and purposes).
Anyway, long story short, this is what I've done when I had to encode the RGBA stills:

```
FFImageSource("\\mibctvan000\Ingest\MEDIA\temp\LUT conversion for stills\MicrosoftTeams-image (1).png")

my_alpha=ShowAlpha(pixel_type="RGB24")


RemoveAlphaPlane()

ConvertBits(16)
ConvertToPlanarRGB(matrix="PC.709", interlaced=false)

Cube("\\mibctvan000\Ingest\MEDIA\temp\LUT conversion for stills\3a_BT709_HLG_Type1_Display_DirectMapping_nocomp-v1_5 1.cube", interp=1, fullrange=1)

my_HLG=last

ConvertBits(my_alpha, 16)
ConvertToPlanarRGB(matrix="PC.709", interlaced=false)

Cube("\\mibctvan000\Ingest\MEDIA\temp\LUT conversion for stills\3a_BT709_HLG_Type1_Display_DirectMapping_nocomp-v1_5 1.cube", interp=1, fullrange=1)

ConverttoY(matrix="PC.2020")


my_alpha_HLG=last


AddAlphaPlane(my_HLG, my_alpha_HLG)
```


So, by re-arranging what I've done to your use case, your script would become:

```
MaskSubMod("D:/afd/a-mmrq14.ass", 1920, 1080, 23.97599983215332, 51424)

#Save alpha channel
my_alpha=ShowAlpha(pixel_type="RGB24")

#From BT709 to PQ without alpha
RemoveAlphaPlane()
ConvertBits(16)
ConvertToPlanarRGB(matrix="PC.709", interlaced=false)
DGCube("D:/afd/BT709_to_PQ.cube")
my_PQ=last

#From BT709 to PQ only alpha
ConvertBits(my_alpha, 16)
ConvertToPlanarRGB(matrix="PC.709", interlaced=false)
ConvertToPlanarRGB(matrix="PC.709", interlaced=false)
DGCube("D:/afd/BT709_to_PQ.cube")
ConverttoY(matrix="PC.2020")
my_alpha_PQ=last

#Add PQ converted alpha back to PQ converted RGB
AddAlphaPlane(my_PQ, my_alpha_PQ)
```


Now, I commented the code to make it easier.
It's still a bit convoluted, though, so I'll leave the issue open until I'll add it to LinearTransformation() so that I can handle it automatically and properly support RGBA 'cause I feel like this is something the function should do automatically.

I think I deserve a cappucino now. :P

**Comment by FranceBB** [comment]
What's the actual error outputted?
